bug228.scala:11: constructor AccessibleObject cannot be accessed in Foo
  val o = new AccessibleObject;
              ^
one error found
