S4.scala:5: stable identifier required, but a found.
    def foo(x: a.Inner) = x;
               ^
one error found
